### ISSUE TITLE
Activity: Experience’s cover photo is displayed at 4:3 ratio

### ISSUE THREAD

**Issue by NikosVrakas** [EvansPie/friskal#57]
Occasionally i face that behavior with the cover photos. The photo is displayed correctly if i kill the app and restart it. ![57DB77E7-74DA-45C1-98B1-4A2BF9C5D670.jpeg](https://images.zenhubusercontent.com/5d7fc1afc6d30e0001febb75/483df145-2fd7-4205-b5ca-797764cdc6c1)

**Comment by EvansPie** [comment]
@NikosVrakas does this happen momentarily or it stays like that? Have you seen it in both platforms or just Android?

**Comment by NikosVrakas** [comment]
Haven’t seen it since the latest 2 releases... i think momentarily in some cover photos.

**Comment by EvansPie** [comment]
Can't do much about that. It occurs momentarily in low-end devices that need sometime to calculate image's height & width before they scale the image to fill the view. Hi-end devices (e.g. iPhone) do it as well but very quickly. So you either see a quick flash or nothing at all since the initial dimensions didn't have the time to render on screen.
