### ISSUE TITLE
Profile: "Experiences" text is not fully visible due to big font  

### ISSUE THREAD

**Issue by NikosVrakas** [EvansPie/friskal#8]

**Comment by EvansPie** [comment]
@NikosVrakas Please provide a screenshot and what device was used.

**Comment by NikosVrakas** [comment]
[Uploading... EBA7C458-CF78-400F-90C6-B00A3D16766A.png ]

**Comment by EvansPie** [comment]
@NikosVrakas,  @hmakridis  that's why my solution didn't work:
https://github.com/facebook/react-native/issues/20906

And probably my Android screen is big enough to not encounter it.

I'm using the property `adjustsFontSizeToFit ` (RN Text property) in order to not make the font size small for everyone, but just the people that have smaller screens. However it seems that there's a bug and it only works on iOS.

The only way to fix it is to make the font size smaller for everyone. At the moment it's 16px. Do you want me to proceed?

**Comment by NikosVrakas** [comment]
Yes Vangeli, i think decreasing font size would be ideal because it seems big on my android device, at least.

But what you mean by “everyone”? It will affect both ios and android?

**Comment by NikosVrakas** [comment]
No improvements in 1.0.15

**Comment by NikosVrakas** [comment]
I think that depends on androids display setting see ticket #54
